---
# A local development environment
version: '3'

networks:
  bbqlaser:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.69.0/24

services:

  nginx:
    image: nginx:alpine
    command: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - bbqlaser

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
    networks:
      - bbqlaser
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: mysqld
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    networks:
      - bbqlaser

  composer: # exits
    image: composer:latest
    restart: 'no'
    command: install
    volumes:
      - ../src:/app

  node: # exits
    image: node:latest
    working_dir: /app
    volumes:
      - ../src:/app
    command: npm install
