---
version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
    networks:
      - mynet
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - mynet
  mysql:
    build:
      context: ./mysql
    env_file:
      - ./.env
    networks:
      - mynet
  composer:
    build:
      context: ./composer
    restart: 'no'
    command: install
    volumes:
      - ../src:/app

networks:
  mynet:
    driver: bridge
