---
# A local development environment
version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - bbqlaser
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
    networks:
      - bbqlaser
  mysql:
    build:
      context: ./mysql
    env_file:
      - ./mysql/.env
    networks:
      - bbqlaser
  composer:
    image: composer:latest
    restart: 'no'
    command: install
    volumes:
      - ../src:/app
  node:
    image: node:latest
    working_dir: /app
    volumes:
      - ../src:/app
    command: npm install

networks:
  bbqlaser:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.69.0/24
